@startuml
allowmixing
skinparam nodesep 1ß
skinparam ranksep 50

actor USER

component "<<MCP Host / UI Client>>\n[[https://github.com/danny-avila/LibreChat Librechat]]" as UI {
    port "3080" as UIP
    component "<<MCP Client>>" as CLIENT
    component "<<MCP Server>>\nOpenAPI Adapter\n[[https://github.com/ivo-toby/mcp-openapi-server mcp-openapi-server]]" as OAA
}

component "<<LLM Adapter>>\nOllama " as OLLAMA {
    port "11434" as OP
    database "Ollama Data\n* <<LLM>> DeepSeek\n* <<LLM>> Phi3" as LLM
}

component "<<[[https://www.restfulobjects.org/spec/1.0/about.html Restful Objects API]]>>\nApache Causeway" as RO {
    port "8080" as ROP
}

OAA --> ROP : RESTful API
UI <--> OP
CLIENT -> OAA
USER --> UIP

note top of UI
    <b>librechat.yaml
    configures MCP Client & Server settings.
    The OpenAPI adapter could be configured
    as a standalone docker service, but this
    would then require to use http instead of stdio.
end note

note bottom of LLM
    Small, Quantized, Distilled models
    allow use on consumer hardware
end note

@enduml
